"""Environment / .env file support."""

from __future__ import annotations

import os
import re
from pathlib import Path
from typing import Any


class EnvMerger:
    """Load, merge and write .env / environment-style files."""

    ENV_LINE = re.compile(
        r"""^\s*(?:export\s+)?([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*)$"""
    )

    def load(self, path: str | Path) -> dict[str, str]:
        """Load a .env file into a dict."""
        path = Path(path)
        result: dict[str, str] = {}
        if not path.exists():
            return result

        for line in path.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            m = self.ENV_LINE.match(line)
            if not m:
                continue
            key, value = m.group(1), m.group(2)
            if (value.startswith('"') and value.endswith('"')) or (
                value.startswith("'") and value.endswith("'")
            ):
                value = value[1:-1]
            result[key] = value
        return result

    def merge_files(
        self,
        files: list[str | Path],
        *,
        include_os: bool = False,
    ) -> dict[str, str]:
        """Merge multiple .env files. Later files override earlier ones."""
        result: dict[str, str] = {}
        if include_os:
            result.update({k: v for k, v in os.environ.items()})

        for f in files:
            data = self.load(f)
            result.update(data)
        return result

    def save(self, data: dict[str, str], path: str | Path) -> None:
        """Write a dict back to a .env file."""
        lines = []
        for key, value in sorted(data.items()):
            if " " in value or "#" in value or '"' in value or "'" in value:
                value = '"' + value.replace('"', '\\"') + '"'
            lines.append(f"{key}={value}")
        Path(path).write_text("\n".join(lines) + "\n", encoding="utf-8")

    def to_export_script(self, data: dict[str, str]) -> str:
        """Generate a shell export script."""
        lines = ["#!/usr/bin/env bash", "# Generated by OpenComb"]
        for key, value in sorted(data.items()):
            safe = value.replace("'", "'\"'\"'")
            lines.append(f"export {key}='{safe}'")
        return "\n".join(lines) + "\n"
